# _config.yml - Base config used in production

# Markdown
markdown : kramdown

#Syntax Highlighting
highlighter: rouge

# Outputting
permalink : pretty
timezone: Europe/London

# Site Variables
title : Thoughts On Frontend Development
description : Web design including UI, UX, HTML, CSS, JavaScript, Node and Cybernetics
url : https://vincentp.me
available: true
webmentionTestUrl: false

#Get Webmentions using Jekyll-Get
jekyll_get:
  - data: webmention
    json: 'https://webmention.io/api/mentions?domain=vincentp.me&token=aSJ1xen947l7hz4e42KlYw'
    cache: false

# Exclude Files
exclude:
  - "postcss.config.js"
  - "Gemfile"
  - "Gemfile.lock"
  - "package.json"
  - "node_modules"
  - "LICENSE"
  - ".cache"
  - ".github"
  - ".gitignore"
